# Generated by Django 5.2 on 2025-11-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_payrollentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='pay_frequency',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Bi-Weekly', 'Bi-Weekly'), ('Weekly', 'Weekly')], default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
