# Generated by Django 5.2 on 2025-11-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_staffprofile_last_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housekeepingtask',
            name='status',
            field=models.CharField(choices=[('DIRTY', 'Dirty'), ('IN_PROGRESS', 'In Progress'), ('CLEAN', 'Clean'), ('MAINTENANCE', 'Maintenance')], default='DIRTY', max_length=20),
        ),
    ]
