# Generated by Django 5.2 on 2025-11-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_hotel_default_currency_hotel_maintenance_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_types/'),
        ),
    ]
