# Generated by Django 5.2 on 2025-11-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
