# Generated by Django 5.2 on 2025-11-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0014_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CARD', 'Credit Card'), ('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('PAYHERE', 'PayHere'), ('PAYHERE_SANDBOX', 'PayHere Sandbox')], max_length=20),
        ),
    ]
