# Generated by Django 5.2 on 2025-11-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0015_payment_status_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
