# Generated by Django 5.2 on 2025-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0016_hotel_cancellation_policy_hotel_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='default_currency',
            field=models.CharField(default='LKR', max_length=10),
        ),
    ]
