# Generated by Django 5.2 on 2025-11-25 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0017_alter_hotel_default_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name', max_length=100)),
                ('message', models.CharField(help_text='Text shown to customer', max_length=255)),
                ('link_text', models.CharField(blank=True, max_length=50, null=True)),
                ('link_url', models.CharField(blank=True, max_length=200, null=True)),
                ('style', models.CharField(choices=[('info', 'Blue (Info)'), ('success', 'Green (Success)'), ('warning', 'Orange (Warning)'), ('error', 'Red (Alert)')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='Hotel.hotel')),
            ],
        ),
    ]
